require "csv"
require 'pry'

csv = <<CSV
name,location,grade
77 BURGER,77 PEARL ST,A
ADRIENNE'S PIZZA BAR,54 STONE STREET,A
ALL AMERICAN DELI,42 WATER STREET,A
ANGLERS CLUB OF NEW YORK,101 BROAD STREET,A
ANTICA RISTORANTE,8 STONE ST,C
AUNT BUTCHIES CAFE,4 SOUTH STREET,A
AUNTIE ANNE'S/RED MANGO,4 SOUTH ST,A
BATTERY GARDENS RESTAURANT,1 BATTERY PARK PLAZA,A
BAVARIA BIERHOUSE/THE CAULDRON,19 S WILLIAM ST,B
BECKETT'S,81 PEARL STREET,A
BENTO NOUVEAU,32 BROADWAY,A
BINGO DELI,77 PEARL STREET,A
BLACK FOX,85 BROAD ST,A
BOBBY VAN'S STEAKHOUSE,25 BROAD STREET,A
BOMBAY'S,60 PEARL STREET,A
BROADSTONE BAR & KITCHEN,88 BROAD ST,A
BURGER BURGER,77 PEARL STREET,A
BURGER KING,16 BEAVER STREET,A
CAFE GRUMPY,20 STONE ST,A
CAFE PLAZA DELI,11 BROADWAY,A
CAPPONE'S SALUMERIA,1 NEW YORK PLZ,A
CENTRAL MARKET ALL AMERICAN GRILL,4 SOUTH STREET,A
CHAMP GOURMET,30 BROAD STREET,B
CHIPOTLE MEXICAN GRILL,2 BROADWAY,A
CHOP'T,1 NEW YORK PLZ,A
CLAUDIA'S COFFEE SHOP,125 BROAD STREET,A
COSI,55 BROAD STREET,A
DA VINCI PIZZA,44 WATER ST,A
DEAD RABBIT TAVERN,30 WATER STREET,A
DELMONICOS,56 BEAVER STREET,A
DIG INN SEASONAL MARKET,80 BROAD ST,A
DOS TOROS,1 STATE ST,A
DUNKIN',90 BROAD ST,A
DUNKIN',33 BEAVER ST,A
EAT-A-BAGEL (ANDREW J. BARBERI FERRY),12 WHITEHALL FERRY TERMINAL,A
EAT-A-BAGEL - BOAT SPIRIT OF AMERICA,12 WHITEHALL FERRY TERMINAL,A
EAT-A-BAGEL--John Marchi Ferry,12 WHITE HALL FERRY TERMINAL,A
EAT A BAGEL (On the Guy V. Molinari Ferry),0 WHITEHALL FERRY TERMINAL,A
EL TORO MEXICAN GRILL,69 NEW STREET,A
FIKA,66 PEARL ST,A
FINANCIER PATISSERIE,62 STONE STREET,A
FIVE IRON GOLF,22 STONE ST,A
FLAVORS,42 BROADWAY,A
FLAVORS,27 WHITEHALL STREET,A
FRAUNCES TAVERN,54 PEARL STREET,B
FRIED FRANK CAFETERIA,1 NEW YORK PLAZA,A
GFG BAKERY CAFE,32 BROADWAY,A
GIGINO AT WAGNER PARK,20 BATTERY PLACE,A
GREGORY'S COFFEE,42 BROADWAY,A
GROUND CENTRAL COFFEE COMPANY,2 COENTIES SLIP,A
GUARDIAN LIFE EMPLOYEE CAFETERIA,7 HANOVER SQUARE,A
HALE & HEARTY SOUP,55 BROAD STREET,A
HANOVER GOURMET DELI,3 HANOVER SQ,A
HARRY'S CAFE/HARRY'S STEAK,1 HANOVER SQUARE,B
HILTON GARDEN INN,6 WATER ST,A
HUGHES HUBBARD & REED LLP,1 BATTERY PARK PLAZA,A
India House Club,1 HANOVER SQUARE,A
INSOMNIA  COOKIES,76 PEARL ST,A
JOE & THE JUICE BROAD ST,40 BROAD ST,A
JOSEPH'S RISTORANTE,3 HANOVER SQUARE,A
JPMC/STARBUCKS,4 NEW YORK PLZ,A
JUSTINO'S PIZZERIA,77 PEARL ST,C
JUST SALAD,90 BROAD ST,A
KOME WAZA,40 WATER ST,A
LATTE ART,15 STONE ST,A
LENITA TAQUERIA,7 HANOVER SQ,A
LEN'S PAPAYA,4 SOUTH STREET,A
LEONIDAS,3 HANOVER SQUARE,A
LEO'S BAGELS,3 HANOVER SQUARE,A
LE PAIN QUOTIDIEN,85 BROAD ST,A
LIBERTY CAFE (JFK FERRY),12 WHITEHALL FERRY TERMINAL,A
LUKE'S LOBSTER,26 SOUTH WILLIAM STREET,A
MAD DOG & BEANS,83 PEARL STREET,A
MORGAN STANLEY EMPLOYEE CAFETERIA,1 NEW YORK PLAZA,A
MURPHY'S TAVERN,6 STONE STREET,C
NAYA EXPRESS,1 NEW YORK PLZ,A
NEW GOLDEN CHOPSTICKS,77 PEARL ST,A
NO. 1 RESTAURANT,10 S WILLIAM ST,A
OBAO NOODLES & BBQ,38 WATER STREET,B
PEARL STREET HAMPTON INN,32 PEARL ST,A
PIER A HARBOR HOUSE,22 BATTERY PL,A
PIZZA ETALIA,20 BEAVER ST,A
PIZZA PLUS,4 SOUTH ST,A
PLAYA BOWLS,1 NEW YORK PLZ,A
POKEBAB,80 BROAD ST,A
POKE GREEN,3 HANOVER SQ,A
POTBELLY SANDWICH WORKS,90 BROAD STREET,A
PRANZO,34 WATER ST,A
PRET A MANGER,60 BROAD STREET,A
PRET A MANGER,50 BROADWAY,A
PRIMARY,26 BROADWAY,A
RAMEN/KUNG FU TEA,9 BROADWAY,B
RESERVE CUT,40 BROAD ST,A
RETRO FITNESS,1 NEW YORK PLZ,A
ROCKWELL'S COFFEE SHOP,105 BROAD ST,A
ROSEN'S CAFE,2 BROADWAY,A
ROUTE 66 AMERICAN BBQ,79 PEARL ST,A
RUBEN'S EMPANADAS,77 PEARL STREET,A
SABI SUSHI,1 NEW YORK PLZ,A
SCHNIPPERS,1 NEW YORK PLZ,A
SHORTY'S,62 PEARL ST,A
SOPHIE'S RESTAURANT(Entrance on 73 New Street),26 BROADWAY,A
SPRINGBONE KITCHEN,74 PEARL ST,A
STARBUCKS,2 BROADWAY,A
STARBUCKS,1 NEW YORK PLZ,A
STARBUCKS,55 BROAD ST,A
STONE STREET TAVERN (@ 52 STONE ST),85 PEARL STREET,A
SUBWAY,11 BROADWAY,B
SUBWAY,30 BROAD ST,A
SUBWAY,28 WATER ST,A
SULLIVAN & CROMWELL,125 BROAD STREET,A
TABLE GREEN,0 BATTERY PARK,A
TABLE GREEN CAFE,0 BATTERY PARK,A
TERRACE FISH & CHIPS,77 PEARL STREET,A
THE DUBLINER,45 STONE STREET,A
THE GROTTO,69 NEW STREET,A
THE LIBERTY CAFE (S.I. NEWHOUSE),12 WHITEHALL FERRY TERMINAL,A
THE PORTERHOUSE,66 PEARL ST,A
THE WAGNER HOTEL,2 WEST ST,A
TORO LOCO,15 STONE ST,A
TRADER'S EXPRESS DELI,22 BEAVER STREET,A
UNDERDOG,55 STONE STREET,A
UNDERGROUND PIZZA,2 WILLIAM STREET,A
UNITED FEDERATION OF TEACHERS,52 BROADWAY,A
WAVES CAFE,0 PETER MINUIT PLAZA,A
WENDY'S,4 SOUTH ST,A
WHITE HORSE TAVERN,25 BRIDGE ST,A
YIP'S RESTAURANT/JUICE VITALITY,18 BEAVER STREET,B
CSV


CSV.parse(csv, headers: true) do |row|
    Restaurant.create(name: row.fields[0], location: row.fields[1], grade: row.fields[2] )
  end


